#!/bin/sh
set -e
export CHARM_HOST=cloud.charm.sh
export CHARM_HTTP_PORT=35354

echo "Building the site..."
cd ~/Documents/site && hugo
echo "Updating CharmFS site..."
charm fs cp -r public charm:site
echo "Publishing to Tavern..."
tavern publish site/public
