#!/bin/sh
set -e
# Used by Tavern's client and charm client
export CHARM_HOST=cloud.charm.sh
export CHARM_HTTP_PORT=35354
# Used by Tavern's server
export CHARM_SERVER_URL=https://$CHARM_HOST:$CHARM_PORT

echo "Building the site..."
cd ~/Documents/site && hugo
echo "Updating CharmFS site..."
charm fs cp -r public charm:site
echo "Publishing to Tavern..."
tavern publish site/public
